version: '3.8'

services:
  web:
    build: .
    container_name: my_flask_app
    ports:
      - "5002:5002"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5002
